// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'scheduleInputs': string;
  'target': string;
  'targetDetails': string;
}
export const cssExports: CssExports;
export default cssExports;
