// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'navButtons': string;
  'navlink': string;
}
export const cssExports: CssExports;
export default cssExports;
